# bot 账号
qq:
  account: your qq number
  password: your qq password or 32bit md5

# bot 主人
master: your master qq

# bot 群聊
groups:
  # 无需手动配置
  # 群内有人发送消息后会自动在此处添加群聊相关信息

# bot 信息
info:
  released: 2021/3/3
  version: yumemi beta 0.5.1
  index: http://www.littlemaple.club/
  docs: https://docs.littlemaple.club/#/help/
  changelogs: https://docs.littlemaple.club/#/changelog/

# bot 配置
# 除非你知道自己在做什么，以下一般无需修改
config:
  # https://github.com/takayama-lily/oicq/blob/master/client.d.ts#ConfBot
  log_level: debug
  platform: 1